grasp:
  step: 20
  substep: 10
  cdist: 0.001    # target hand-object contact distance
  filter:
    limit:
      thre: 0.0  # max value out of the joint qpos limit
    collision: 
      hh_thre: 0.  # min hand-hand distance for collision-free grasp
      ho_thre: 0.  # min hand-object distance for collision-free grasp
    contact: 
      thre: 0.002  # max hand-object distance for a valid contact
      check_body: True  # check if the required contact bodies are in contact
    qp:
      thre: 0.001  # the qp error should be less than this threshold
      miu_coef: [0.6, 0.02]  # tangential and torsional friction coefficient
  
pregrasp:
  step: 20
  substep: 10  
  cdist: 0.045    # target hand-object contact distance
  filter:
    limit:
      thre: 0.0  # max value out of the joint qpos limit
    collision: 
      hh_thre: 0.0  # min hand-hand distance for collision-free pregrasp
      ho_thre: 0.04  # min hand-object distance for collision-free pregrasp

cust_log_dir: ${log_dir}