name: dexjoco
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
dependencies:
  - python=3.11
  - pip
  - av
  - glfw
  - gymnasium=1.0.0
  - mujoco=3.4.0
  - "numcodecs<0.16"
  - numpy==1.26.4
  - scipy
  - "zarr<3"
  - pip:
      - -e ./dexjoco
      - -e ./openpi/packages/openpi-client
